function UCVISTimeline(n){var i='<div style="display:none">\t{{startDate}}\t{{endDate}}\t{{item}}<\/div><br /><div id="visualization" ><\/div><div id="key" style="display:flex; margin-top: 10px">\t<div style="display:flex;">\t\t<div style="background: #dddddd; height:10px; width:10px; margin: 4px"><\/div> <label>Pending<\/label>\t\t<div style="background: #D5DDF6; height:10px; width:10px; margin: 4px"><\/div> <label>Default<\/label>\t<\/div><\/div>',u={},t;Mustache.parse(i);var f=0,e=0,o=0,r;this.show=function(){r=n(this.getContainerControl());f=0;e=0;o=0;this.setHtml(Mustache.render(i,this,u));this.renderChildContainers();n(this.getContainerControl()).find("[data-event='Click']").on("click",this.onClickHandler.closure(this)).each(function(n){this.setAttribute("data-items-index",n+1)});n(this.getContainerControl()).find("[data-event='click2']").on("click2",this.onclick2Handler.closure(this)).each(function(n){this.setAttribute("data-items-index",n+1)});n(this.getContainerControl()).find("[data-event='DateRangeChanged']").on("daterangechanged",this.onDateRangeChangedHandler.closure(this)).each(function(n){this.setAttribute("data-items-index",n+1)});this.Init2()};this.Scripts=[];this.Init2=function(){var e,v,o,u,i,y,t,s,h,f;try{console.log(this.HolidayNameCollection);console.log(this.HolidayValueCollection);const d=document.createElement("style"),g=JSON.parse(this.HolidayValueCollection),rt=JSON.parse(this.HolidayNameCollection);e="";g.forEach((n,t)=>{e+=`
							.vis-time-axis .vis-minor.vis-grid${n} {
								background: #FAF2CC;
							}
							
							.vis-text${n}::after {
								content: " (${rt[t]})";
								font-size: 10px;
							}
							`});d.innerHTML=e;document.head.appendChild(d);function nt(n){const t=`${n.getFullYear()}`.slice(-2),i=("0"+(n.getMonth()+1)).slice(-2),r=("0"+n.getDate()).slice(-2);return`${i}/${r}/${t}`}const k=this;var r=JSON.parse(this.events),c=JSON.parse(this.groups),l=JSON.parse(this.leavetypes),d=moment().minutes(0).seconds(0).milliseconds(0),a=new vis.DataSet;for(t=0;t<c.length;t++)v=c[t],a.add(v);for(o=new vis.DataSet,t=0;t<r.length;t++)u=r[t],u.style="color: red; background-color: pink;",o.add(u);console.log(u);var p=document.getElementById("visualization"),w={groupOrder:"content",orientation:{axis:"both"},timeAxis:{scale:"day",step:1},showWeekScale:!0,start:this.startDate,end:this.stopDate,zoomable:!0,verticalScroll:!0,horizontalScroll:!0,zoomKey:"ctrlKey",format:{minorLabels:{day:"ddd DD"}},maxHeight:"100%"},f=n(window).height(),b=n("#visualization").height();console.log(f+" - "+b);i=new vis.Timeline(p);i.setOptions(w);i.setGroups(a);i.setItems(o);i.on("rangechange",function(){it()});i.on("click",function(n){console.log(n.item);console.log(i.itemSet.items);k.item=n.item;k.Click();let t=window.scrollY;console.log(t)});i.on("rangechanged",function(n){k.newStartDate=nt(n.start);k.newStopDate=nt(n.end);var t=new vis.DataSet;k.RangeChangedFromUC=!0});function tt(n,t){var i=document.getElementsByClassName(n),r;for(let n=0;n<i.length;n++)r=i[n],r.style.background=t}function it(){for(var n,t=0;t<r.length;t++)n=r[t],tt(`${n.id}`,n.color),tt(n.className,n.color)}for(y=document.getElementById("key"),t=0;t<l.length;t++)s=l[t],h=document.createElement("div"),h.innerHTML=`
							<div style="display:flex;">
							<div style="background: ${s.LeaveTypeColorApproved}; height:10px; width:10px; margin: 4px; margin-left: 10px"></div> <label>${s.LeaveTypeName}</label>
							</div>
							`,y.appendChild(h);function ot(){const n=document.querySelectorAll(".vis-text.vis-day16.vis-april");n.forEach(n=>{console.log(n.innerHTML),n.innerHTML+=" (Holiday Name)"})}it();f=n(window).height();const ut=document.getElementById("visualization");function ft(t){for(let i of t)i.contentRect.height>f-250&&(n("#visualization").css("height",f-250),n("#visualization").css("overflow","auto"))}const et=new ResizeObserver(ft);et.observe(ut);g.forEach(n=>{const t=document.querySelectorAll(`.vis-text${n}`);console.log(`.vis-text${n}`,t)})}catch(k){console.error(k)}};this.SetItems=function(n){var n,r,t,i;for(this.events=n,console.log(this.events),n=JSON.parse(this.events),r=new vis.DataSet,t=0;t<n.length;t++)i=n[t],console.log(i),r.add(i)};this.Refresh=function(n,t){this.events=n;this.groups=t;this.show()};this.onClickHandler=function(n){if(n){var t=n.currentTarget;n.preventDefault()}this.Click&&this.Click()};this.onclick2Handler=function(n){if(n){var t=n.currentTarget;n.preventDefault()}this.click2&&this.click2()};this.onDateRangeChangedHandler=function(n){if(n){var t=n.currentTarget;n.preventDefault()}this.DateRangeChanged&&this.DateRangeChanged()};this.autoToggleVisibility=!0;t={};this.renderChildContainers=function(){r.find("[data-slot][data-parent='"+this.ContainerName+"']").each(function(i,r){var e=n(r),f=e.attr("data-slot"),u;u=t[f];u||(u=this.getChildContainer(f),t[f]=u,u.parentNode.removeChild(u));e.append(u);n(u).show()}.closure(this))}}